name = "lapce-omnisharp"
version = "0.1.0"
display-name = "OmniSharp"
author = "AsriFox"
description = "OmniSharp (C#) server for Lapce"
wasm = "lapce-omnisharp.wasm"

[activation]
language = ["csharp"]
workspace-contains = ["*.csproj"]

[config."volt.serverPath"]
default = ""
description = "Path to OmniSharp executable; an empty string points to the bundled binary."
